refactor: consolidate pool implementation
osmosis-labs/osmosis pull request #1498
Opened 2022-05-16 14:29 UTC by alexanderbez

Closes: #1225

- Move balancer and amm logic into a single `pool.go` file
- Move `PoolParams` to `pool_params.go` file

2022-05-16 14:31 UTC, alexanderbez commented
@ValarDragon the question remains, do we want `pool_test.go` to be in package `balancer` or `balancer_test`? If the latter, we need to make `Pool#setInitialPoolAssets` a public API.

2022-05-18 01:29 UTC, ValarDragon commented
I'm down for it to be in either package tbh

2022-06-16 02:21 UTC, mattverse reviewed
Per deleting `amm.go`, did we decide to remove separating the amm logic and the pool logic by using two different files `amm.go` and `pool.go`?

2022-06-16 02:21 UTC, mattverse commented on x/gamm/pool-models/balancer/pool_params.go
> +package balancer
I love how we made a separate file for pool params!

2022-06-16 02:35 UTC, mattverse requested changes
Can we also change stableswap package from stableswap_pool.go -> pool.go to better achieve consolidation between the packages? I'm also down to leaving balancer_pool.go

2022-06-16 18:53 UTC, alexanderbez commented
I'm going to need to rebase this again unfortunately, a bit annoying but w.e. The idea is just to consolidate the pool logic into a single file along with the tests.

2022-06-17 02:07 UTC, mattverse commented
Oh interesting, I thought we were trying to separate out the pool methods and the core math logic in two different files? 

If we were to change the decision to move towards a single pool.go file, I think we should make the same changes in stableswap package as well or do you think that change is out of scope for this PR?

2022-06-24 22:18 UTC, alexanderbez commented
Conflicts are too large here to warrant resolving them. Instead re-opened a new PR: https://github.com/osmosis-labs/osmosis/pull/1868

2022-06-24 22:18 UTC, closed without merging