Lostak/swap fee for tx/v2
osmosis-labs/osmosis pull request #1675
Opened 2022-06-06 05:31 UTC by lostak

Closes: #1139

## What is the purpose of the change

Swap fees paid along the route of swaps are added to the Tx fee when paying for gas.

## Brief Changelog

- Add `GetSwapFee(ctx sdk.Context, poolId uint64) (sdk.Dec, error)` to `swap.go` and to the `GammKeeper` in the `expected_keepers` for the `txfees` module
- Add interfaces for `MsgSwapExactAmountIn` and `MsgSwapExactAmountOut` in `msg_swap.go`
- `AnteHandle` now treats `SwapMsgRoute` msgs differently when checking a fee but other msgs use the same logic as before

## Testing and Verifying

Tests are needed

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (no)
  - How is the feature or change documented? (not documented)

2022-06-07 01:10 UTC, lostak commented on x/gamm/types/msg_swap_sybil.go
> +)
Should this be expanded to include Join/Exit swap msgs?

2022-06-07 01:49 UTC, lostak commented on x/gamm/types/msg_swap_sybil.go
> +)
Changes would be
https://github.com/osmosis-labs/osmosis/blob/6f00aa702e2e72ed20ab82cba87256b7a043307e/x/gamm/types/msg_swap_sybil.go#L10-L20
https://github.com/osmosis-labs/osmosis/blob/6f00aa702e2e72ed20ab82cba87256b7a043307e/x/gamm/types/msg_swap_sybil.go#L46-L58

2022-06-07 21:11 UTC, lostak commented on x/gamm/types/msg_sybil.go
> +
Should sysbil resistant fees be added for superfluid/incentivized pool delegate/undelegate?

2022-06-15 09:30 UTC, lostak commented
[Relevant diagram depicting current implementation and PR's implementation](https://mm.tt/map/2327084301?t=14EgCd3vN7)

2022-06-16 06:02 UTC, mattverse commented
Oh wow is the diagram created via software?

2022-06-16 06:05 UTC, lostak commented
@mattverse no, did it own my own but I am confident in its accuracy

2022-06-16 06:06 UTC, lostak commented
> Oh wow is the diagram created via software?

No, I created it on my own, but I am confident that it is accurate

2022-06-16 18:29 UTC, alexanderbez reviewed
There is a lot of commented out code here @lostak. What's up with that?

2022-06-17 07:15 UTC, lostak commented
@alexanderbez I attempted to apply the same functionality for joins and exits involving swaps but ran into issues with the information provided in the messages. The commented code should be moved to another branch.

2022-06-17 14:30 UTC, p0mvn requested changes
Hi @lostak 

Thanks so much for this change.

I haven't finished reviewing this in detail yet. I would like to request to test the newly added logic. Please let me know once that's ready

2022-06-17 14:30 UTC, p0mvn commented on x/gamm/keeper/swap.go
> +func (k Keeper) GetSwapFeeFromPoolId(ctx sdk.Context, poolId uint64) (sdk.Dec, error) {
Let's test this please

2022-06-17 14:30 UTC, p0mvn commented on x/gamm/types/msg_sybil.go
> +func (msg MsgSwapExactAmountOut) PoolIdOnPath() []uint64 {
I would like to see this covered by tests

2022-06-17 14:30 UTC, p0mvn commented on x/txfees/keeper/sybil.go
> +	return Sybil{GasPrice: s.GasPrice, FeesPaid: fp}, nil
What is the purpose for returning a new `Sybil`?

It seems to me that we can make `(s *Sybil)` (pointer receiver) and modify the existing instance without having to create new

2022-06-17 14:30 UTC, p0mvn commented on x/txfees/keeper/feetokens.go
> +// GetTotalSwapFee gets the total swap fee for a swap message along a route of pool ids
```suggestion
// getTotalSwapFee gets the total swap fee for a swap message along a route of pool ids
```

2022-06-17 14:30 UTC, p0mvn commented on x/txfees/keeper/feetokens.go
> +func (k Keeper) getFeesPaid(ctx sdk.Context, poolIds []uint64, denomPath []string, token sdk.Coin) (sdk.Coin, error) {
test please

2022-06-17 20:51 UTC, lostak commented on x/gamm/types/msg_sybil.go
> +package types
The reason I ended up moving them from `msg_swap.go` to `msg_sybil.go` was to keep `msg_swap.go` purely for swap messages, and to allow `msg_sybil.go` to be more abstract and be satisfied by msgs like join/exit with swap msgs.
If a join/exit with swap msg were to satisfy the methods of `SybilResistantFee`, then `TokenDenomsOnPath` would be implemented in `msg_sybil.go` but I understand your point. To that end, do you think `msg_swap.go` should define methods for msgs like `MsgJoinSwapExternAmountIn`?

2022-06-17 21:06 UTC, lostak commented on x/txfees/keeper/feetokens.go
> +	if len(denomPath) == 1 {
When I started adding support for join/exit with swap msgs, `TokenDenomsOnPath` had to be satisfied and return an array. 
However, this array would only hold the 1 denom for the token in/out and the loop relies on there being 2 denoms per pool id.

2022-06-17 21:27 UTC, lostak commented
@p0mvn Thanks for your review, I've made the changes you've suggested but I still need to add the tests. 
Is there any documentation that you'd suggest to help me better understand how to use the testing suite?

2022-06-19 02:53 UTC, lostak commented
Github's tests were failing because they were not up to date with the main branch.
I moved the changes to a new branch off the up to date main and the tests are passing now.
The new PR is #1823

2022-06-19 07:23 UTC, closed without merging

2022-06-19 09:43 UTC, Naser531900 approved these changes