Feature/add details to join exit pool reponse
osmosis-labs/osmosis pull request #1886
Opened 2022-06-28 08:00 UTC by Ehsan-saradar

## What is the purpose of the change

This PR adds more information to response of join/exit pool handlers so the caller of the transaction in ICA receives these information on acknowledgment.

## Brief Changelog

  - *Added `tokenIn sdk.Coins`, `sharesOut sdk.Int` to return of `JoinPoolNoSwap`*
  - *`share_out_amount` and `token_in` fields to `MsgJoinPoolResponse`*
  - *`token_out` field to `MsgExitPoolResponse`*

## Testing and Verifying

This change added tests and can be verified as follows:

  - *Extended integration test for `TestJoinPoolNoSwap`*

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (no)
  - How is the feature or change documented? (not documented)

2022-06-28 09:45 UTC, mattverse requested changes
Thanks for this PR! I personally think adding responses to messages are super useful. 

Can we make sure we add new test cases and checks for the new fields to ensure they return expected values?

Also, can you drop the changes for `go.mod` and `go.sum` as well? Otherwise, logic itself 
lgtm!

2022-06-28 09:45 UTC, mattverse commented on x/gamm/keeper/pool_service_test.go
> +				_, _, err := keeper.JoinPoolNoSwap(suite.Ctx, suite.TestAccs[1], poolId, types.OneShare.MulRaw(50), sdk.Coins{
Can we add check and test ShareOutAmount and TokenIn returned here is as expected?

2022-06-28 09:45 UTC, mattverse commented on x/gamm/keeper/pool_service_test.go
> +		_, _, err = suite.App.GAMMKeeper.JoinPoolNoSwap(suite.Ctx, joinPoolAcc, poolId, tc.joinPoolShareAmt, sdk.Coins{})
ditto:Can we add check and test ShareOutAmount and TokenIn returned here is as expected?

2022-06-28 12:59 UTC, ValarDragon commented
Needs changelog entry as well

2022-07-07 01:55 UTC, ValarDragon commented
https://github.com/quasar-finance/osmosis/pull/2

2022-07-07 05:03 UTC, mattverse reviewed
Reviewed the changes made in https://github.com/quasar-finance/osmosis/pull/2 Let's merge this once https://github.com/quasar-finance/osmosis/pull/2 gets merged!

2022-07-07 05:03 UTC, mattverse approved these changes

2022-07-07 13:42 UTC, merged