refactor(x/swaprouter): update swaprouter CLI with osmocli; deprecate comparable gamm CLI
osmosis-labs/osmosis pull request #3875
Opened 2022-12-28 16:35 UTC by RusAkh

Closes: #3825

## What is the purpose of the change

Changes cli of `swaprouter` to use osmocli features. Deprecates corresponding cli in `gamm` 

## Documentation and Release Note

not yet

2022-12-30 19:18 UTC, p0mvn approved these changes
utACK. Thanks. Let's wait for one more before merge

2022-12-31 05:22 UTC, p0mvn commented
@RusAkh have you tested each updated CLI command?

It looks like e2e test might be failing

2022-12-31 05:41 UTC, p0mvn requested changes
Please look into e2e test and manually test that every CLI command is working

2022-12-31 14:15 UTC, RusAkh commented
hello @p0mvn I want to clarify something. Should `create-pool` cmd be in `gamm` or `swaprouter`? It Is currently in both gamm and swaprouter

2022-12-31 22:50 UTC, p0mvn commented
> hello @p0mvn I want to clarify something. Should `create-pool` cmd be in `gamm` or `swaprouter`? It Is currently in both gamm and swaprouter

Let's leave it in gamm for now. The reason is that before the e2e upgrade there is no swaprouter module yet. We can change this to swaprouter in the future upgrade.

2023-01-02 16:45 UTC, p0mvn commented
Hi @RusAkh . Could you please rebase this PR? Have you figured out the e2e problems?

2023-01-02 23:11 UTC, ValarDragon commented
We should not break the gamm cli.

2023-01-03 11:34 UTC, RusAkh commented
hello @p0mvn. I did not really find what is wrong with `e2e`. Still looking into that, apologize for the delays

2023-01-03 12:46 UTC, RusAkh commented
https://github.com/osmosis-labs/osmosis/actions/runs/3829193643/jobs/6515616760 the error is pretty weird. Another notional team member had the same weird test fail, so I do not think that it is related to changes in this PR

2023-01-03 19:56 UTC, p0mvn commented
Can you try merging `main` into your branch please? There was an e2e failure in main which is now resolved

2023-01-03 20:07 UTC, p0mvn commented
> We should not break the gamm cli.

@RusAkh based on request, could you please restore the gamm CLI?

2023-01-03 21:56 UTC, RusAkh commented
> > We should not break the gamm cli.
> 
> @RusAkh based on request, could you please restore the gamm CLI?

sure

2023-01-03 21:58 UTC, RusAkh commented
@p0mvn in this [commit](https://github.com/osmosis-labs/osmosis/pull/3875/commits/40d5a91af0503b7f57f758ad6e1026b6866a3c13) I changed usage of `gamm`'s commands to `swaprouter`'s commands in scripts and other stuff. Shall I bring it back as well or it does not really matter?

2023-01-03 22:40 UTC, p0mvn commented on tests/e2e/configurer/chain/commands.go
> +// docker container exec <container id> osmosisd tx swaprouter swap-exact-amount-in <tokeinInCoin> <tokenOutMinAmountInt> --swap-route-pool-ids <swapRoutePoolIds> --swap-route-denoms <swapRouteDenoms
```suggestion
// docker container exec <container id> osmosisd tx gamm swap-exact-amount-in <tokeinInCoin> <tokenOutMinAmountInt> --swap-route-pool-ids <swapRoutePoolIds> --swap-route-denoms <swapRouteDenoms> --chain-id=<id>--from=<address> --keyring-backend=test -b=block --yes --log_format=json
```

2023-01-03 22:40 UTC, p0mvn commented on tests/e2e/configurer/chain/commands.go
> +	cmd := []string{"osmosisd", "tx", "swaprouter", "swap-exact-amount-in", tokenInCoin, tokenOutMinAmountInt, fmt.Sprintf("--swap-route-pool-ids=%s", swapRoutePoolIds), fmt.Sprintf("--swap-route-denoms
```suggestion
	cmd := []string{"osmosisd", "tx", "gamm", "swap-exact-amount-in", tokenInCoin, tokenOutMinAmountInt, fmt.Sprintf("--swap-route-pool-ids=%s", swapRoutePoolIds), fmt.Sprintf("--swap-route-denoms=%s", swapRouteDenoms), fmt.Sprintf("--from=%s", from)}
```

2023-01-03 22:41 UTC, p0mvn commented
> @p0mvn in this [commit](https://github.com/osmosis-labs/osmosis/pull/3875/commits/40d5a91af0503b7f57f758ad6e1026b6866a3c13) I changed usage of `gamm`'s commands to `swaprouter`'s commands in scripts and other stuff. Shall I bring it back as well or it does not really matter?
> 
> UPD: reverted all related to `x/gamm`, lmk about the question above please

We want gamm to be used in e2e because e2e tests logic prior to upgrade and after upgrade.

Prior to upgrade, there is no swaprouter module yet. As a result, e2e would fail.

2023-01-05 15:04 UTC, p0mvn commented
Hi @RusAkh . Any updates here? I'd love to help if any challenges to drive this PR to completion

2023-01-05 17:20 UTC, RusAkh commented
sorry for the delay @p0mvn, I brought back gamm, e2e passes!

2023-01-07 04:01 UTC, p0mvn approved these changes
utACK once the conflict is resolved.

@RusAkh can you please confirm that CLI changes have been manually tested? Thank you

2023-01-07 04:01 UTC, p0mvn commented on go.work.sum
> -github.com/osmosis-labs/osmosis/osmomath v0.0.0-20230105100058-2ad8dafc6e4f/go.mod h1:KrzYoNtnWUH75rj1XAsSR4nymlHFU7jeVOx7/1KMe0k=
Can you please resolve this conflict?

2023-01-07 14:21 UTC, RusAkh commented on go.work.sum
> -github.com/osmosis-labs/osmosis/osmomath v0.0.0-20230105100058-2ad8dafc6e4f/go.mod h1:KrzYoNtnWUH75rj1XAsSR4nymlHFU7jeVOx7/1KMe0k=
resolved

2023-01-07 14:21 UTC, RusAkh commented
> utACK once the conflict is resolved.
> 
> @RusAkh can you please confirm that CLI changes have been manually tested? Thank you

yes, manually tested

2023-01-08 02:05 UTC, p0mvn approved these changes

2023-01-08 02:05 UTC, merged