feat[CL]: delete position from state when completely removed
osmosis-labs/osmosis pull request #4022
Opened 2023-01-14 22:13 UTC by czarcas7ic

Closes: #3951 

## What is the purpose of the change

> Add a description of the overall background and high level changes that this PR introduces

*(E.g.: This pull request improves documation of area A by adding ....*

## Brief Changelog

*(for example:)*
 
  - *The metadata is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *Daemons retrieve the RPC data from the blob cache*

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added unit test that validates ...*
  - *Added integration tests for end-to-end deployment with ...*
  - *Extended integration test for ...*
  - *Manually verified the change by ...*

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no)
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

2023-01-15 01:53 UTC, AlpinYukseloglu approved these changes
LGTM!

2023-01-15 09:46 UTC, mattverse requested changes
AFAIU, we need to make sure we claim the rewards before closing the position. cref: https://github.com/osmosis-labs/osmosis/pull/3961#discussion_r1064841352

2023-01-16 01:51 UTC, czarcas7ic commented
@mattverse @p0mvn I added the claim rewards logic as well as added tests in withdrawPosition to cover this. Nice catch!

2023-01-16 02:54 UTC, p0mvn approved these changes
Nice work

2023-01-16 02:54 UTC, p0mvn commented on x/concentrated-liquidity/lp.go
> +func (k Keeper) withdrawPosition(ctx sdk.Context, poolId uint64, owner sdk.AccAddress, lowerTick, upperTick int64, requestedLiquidityAmountToWithdraw sdk.Dec) (amtDenom0, amtDenom1 sdk.Int, err error
Please update the spec to elaborate on the new functionality

2023-01-16 04:17 UTC, czarcas7ic commented
Updated spec! @mattverse this is good for merge once you clear your requested change!

2023-01-16 08:34 UTC, mattverse approved these changes
LGTM! 🌮

2023-01-16 08:50 UTC, merged