[Internal Audit] MsgSplitRouteSwapExactAmountIn & MsgSplitRouteSwapExactAmountOut
osmosis-labs/osmosis pull request #5247
Opened 2023-05-20 03:01 UTC by stackman27

Closes: #XXX

## What is the purpose of the change

> Add a description of the overall background and high level changes that this PR introduces

*(E.g.: This pull request improves documentation of area A by adding ....*

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added unit test that validates ...*
  - *Added integration tests for end-to-end deployment with ...*
  - *Extended integration test for ...*
  - *Manually verified the change by ...*

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

2023-05-22 12:04 UTC, mattverse requested changes
Main comment is on using the `SwapAmountInRoute` proto directly instead of re-defining them. Unmarshalling part lgtm. 

Also would be great if you can provide logs of using this cli along!

2023-05-22 20:21 UTC, stackman27 commented on x/poolmanager/client/cli/tx.go
> +	var splitRouteProto []types.SwapAmountOutSplitRoute
yup file path is much cleaner :))

2023-05-22 20:21 UTC, stackman27 commented on x/poolmanager/client/cli/tx.go
> +		ParseAndBuildMsg: NewMsgNewSplitRouteSwapExactAmountOut,
yessir

2023-05-22 20:21 UTC, stackman27 commented on x/poolmanager/client/cli/tx.go
> +}
so i tried doing this and ran into parsing issues. basically the JSON parsing wouldn't read the proto structs

2023-05-22 20:34 UTC, stackman27 commented on x/poolmanager/msg_server_test.go
> +			response, err := msgServer.SplitRouteSwapExactAmountIn(sdk.WrapSDKContext(ctx), &types.MsgSplitRouteSwapExactAmountIn{
checking this value seems a lot complex than i thought. You have to check error tolerance and see if it's in bound. It's thoroughly tested here: https://github.com/osmosis-labs/osmosis/blob/main/x/poolmanager/router_test.go#L1851-L1856

I can add test but i dont want to overcomplicate test and also dont just want to copy paste the already tested code. please lmk what you think

2023-05-22 20:34 UTC, stackman27 commented on x/poolmanager/msg_server_test.go
> +				s.Require().NoError(err)
https://github.com/osmosis-labs/osmosis/pull/5247/files#r1201040212

2023-05-22 20:36 UTC, stackman27 commented
Thank you @mattverse for your feedbacks. Resolved most of it and is R4RR

2023-05-22 20:36 UTC, stackman27 commented on CHANGELOG.md
> +  * [#5239](https://github.com/osmosis-labs/osmosis/pull/5239) Implement `GetTotalPoolShares` public keeper function for GAMM.
```suggestion
  * [#5239](https://github.com/osmosis-labs/osmosis/pull/5239) Implement `GetTotalPoolShares` public keeper function for GAMM. 
  
```

2023-05-23 03:39 UTC, mattverse commented on x/poolmanager/client/cli/tx.go
> +}
I should probably work, they are basically same go structs with json labels, did you use the correct json tags? / Do you maybe have a commit or branch I can help debugging with?

2023-05-23 04:41 UTC, mattverse commented
@stackman27 Pushed the fix, also fixed according examples for this, please review the last two commits and see if they make sense!

2023-05-23 04:42 UTC, mattverse approved these changes
LGTM

2023-05-23 18:17 UTC, p0mvn approved these changes
utACK based on earlier review and mostly CLI additions.

Thanks @stackman27

2023-05-23 18:17 UTC, merged