update max-gas-wanted-per-tx to 120M
osmosis-labs/osmosis pull request #5461
Opened 2023-06-08 09:02 UTC by DongLieu

Closes: #5440

update [max-gas-wanted-per-tx](https://github.com/osmosis-labs/osmosis/blob/c6697a5e4b2ccdf216f213a33db7e97b0dd46399/cmd/osmosisd/cmd/root.go#L151) to 120M

2023-06-08 09:03 UTC, DongLieu commented
![image](https://github.com/osmosis-labs/osmosis/assets/93205232/d5d5d97d-cdba-48be-92ae-09e7ff203c1c)

2023-06-08 10:09 UTC, mattverse approved these changes

2023-06-08 13:36 UTC, ValarDragon requested changes
I don't think we should do this, see my comment in issue.

Its the token factory code thats wrong. This is intentionally lower than block gas limit

2023-06-09 12:36 UTC, ValarDragon commented
Closing this in favor of #5468 !

2023-06-09 12:36 UTC, closed without merging