feat(math): add mutative api for BigDec.BigInt()
osmosis-labs/osmosis pull request #6867
Opened 2023-11-13 06:51 UTC by DongLieu

Similar to [PR17803](https://github.com/cosmos/cosmos-sdk/pull/17803) I think we should also have such an API

2023-11-15 07:42 UTC, mattverse requested changes
mostly looks good, requested change for method name change :)

2023-11-15 07:42 UTC, mattverse commented on osmomath/decimal.go
> +func (d BigDec) BigIntMut() *big.Int {
I think ToBigInt is not a suitable method name here, recommending change to the following:
```suggestion
func (d BigDec) ToBigInt() *big.Int {
```

2023-11-20 07:49 UTC, mattverse commented
Please ping me once r4r

2023-11-21 00:56 UTC, DongLieu commented
Ok

2023-11-28 02:28 UTC, DongLieu commented
Thanks you

2023-11-28 09:09 UTC, DongLieu commented
I'm waiting for a PR https://github.com/cosmos/cosmos-sdk/pull/18576 at cosmos hub. Give me more time

2023-12-04 07:00 UTC, closed without merging