osmosis v6 semantic versioning
osmosis-labs/osmosis pull request #793
Opened 2022-01-27 05:54 UTC by faddat

Works Towards: #788 

## Description

Semver for osmosis v6.x

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

2022-01-29 17:16 UTC, mattverse commented
Thanks for this! LGTM! Should be good to merge to 6.x branch

2022-01-29 17:20 UTC, mattverse requested changes
After changing cosmos-sdk version to the original state, this should be good to merge! Thanks for this!

2022-01-29 17:20 UTC, mattverse commented on go.mod
> +	github.com/cosmos/cosmos-sdk v0.45.0
```suggestion
	github.com/cosmos/cosmos-sdk v0.44.5
```

2022-01-29 17:20 UTC, mattverse commented on go.mod
>  )
This is wonderful!

2022-01-29 17:29 UTC, mattverse approved these changes
LGTM! Good to merge to v6.x branch!

2022-01-29 18:38 UTC, ValarDragon approved these changes
Thank you so much!!! This is really big for people to be able to work with Osmosis

2022-01-29 18:38 UTC, merged

2022-02-07 10:40 UTC, marbar3778 commented
could you rename your long-lived branches to release-v6.x as im unable to import v6.x

2022-02-08 07:08 UTC, ValarDragon commented
Hrmm, not sure I undesrtand? Is it that release-v6.x looks better in imports (makes sense / seems reasonable) or that some tooling is failing with `v6.x` and would not fail with `release-v6.x`?

2022-02-08 18:17 UTC, marbar3778 commented
mainly I can't import v6.x into my go mod file. It thinks im trying to import semantic version but .x breaks it

2022-02-08 20:23 UTC, ValarDragon commented
ohh interesting, ok will switch

2022-02-09 09:53 UTC, marbar3778 commented
oh I forgot to edit, but release-6.x is better than v6.x since go errors on this as well

2022-02-10 04:41 UTC, ValarDragon commented
I'm generally confused, I thought you can't import branches in a go.mod. Only releases and commits. When you do `go get repo@branch` it just puts the link to that latest commit in the go.mod. 

https://github.com/golang/go/wiki/Modules#how-to-upgrade-and-downgrade-dependencies

> Using a branch name such as go get foo@master (foo@default with mercurial) is one way to obtain the latest commit regardless of whether or not it has a semver tag.

But I haven't tried much here / you probably understand this better than I do! `go get github.com/osmosis-labs/osmosis/v6@v6.x` is basically the command thats failing rn?

2022-02-10 08:35 UTC, marbar3778 commented
oh nvm the v6@v6 fixed it. I didn't think the /v6 was needed but makes sense. Now on the sdk im running into the same issue