Semantic versioning for v7
osmosis-labs/osmosis pull request #804
Opened 2022-01-29 18:34 UTC by faddat

Works on: #788 

## Description

Semantic versioning for osmosis v7

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

2022-02-03 14:12 UTC, mattverse requested changes
Should be good to merge once go.mod sdk version is reverted to original state!

2022-02-03 14:12 UTC, mattverse commented on go.mod
> +	github.com/cosmos/cosmos-sdk v0.45.0
We should probably remain on v0.44.5 for now!

2022-02-03 20:55 UTC, ValarDragon commented
I am generally lost as to what is standard for golang projects. Is it to make main with breaking changes with one version higher, or is it with the same last major release.

Also how do golang projects do backports with these version import differences :/

2022-02-04 08:03 UTC, mattverse commented
From my knowledge its make breaking changes with one version higher.

2022-02-04 08:06 UTC, mattverse commented
> Also how do golang projects do backports with these version import differences :/
@ValarDragon wdym? Can you give an example ?

2022-02-04 09:23 UTC, faddat commented
You know, there's an issue in this, too.  I'm going to jump off of main a second time, to avoid it.

2022-02-04 09:38 UTC, faddat commented
@ValarDragon if you still want to use mergify, we need to add it to this repo.  I am going to close this one because I think it might add commits of Sunny's not meant for `main`. 

Also seems like some of the wasm tests are trying to import /x/ibc

I think I got halfway through an upgrade of the tests w/ Juno and it should be the same kind of thing so I'll try and fix them.

2022-02-16 00:03 UTC, faddat commented
@mattverse this is complete and I've merged the latest main branch now, too.

2022-02-16 02:19 UTC, mattverse approved these changes
LGTM! Thanks for this @faddat 

In the future, we don't want main to have sem-ver of the next major release, but sem-ver for the latest release, since that would make sense for all the backporting that would be happening. Since we have a major upgrade coming up soon, this PR, in particular, makes sense + super helpful!

2022-02-16 06:16 UTC, ValarDragon commented on x/lockup/keeper/legacy.go
> +package keeper
Lets re-delete this file

2022-02-16 06:21 UTC, ValarDragon approved these changes
Thanks for the in-depth review @mattverse / checking what other projects do as the standard here.

Did a quick skim, and only saw the v7 change + the re-added legacy.go file.

Lets also file an issue to add the semver situation to the contributing.md

2022-02-16 06:22 UTC, ValarDragon commented
Going to go ahead and merge before this is broken by the next PR

2022-02-16 06:22 UTC, merged