BE-658 | Decouple Node releases from SQS
osmosis-labs/osmosis pull request #8886
Opened 2024-12-13 12:16 UTC by deividaspetraitis

Closes: #XXX

## What is the purpose of the change

> Add a description of the overall background and high level changes that this PR introduces

*(E.g.: This pull request improves documentation of area A by adding ....*

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added unit test that validates ...*
  - *Added integration tests for end-to-end deployment with ...*
  - *Extended integration test for ...*
  - *Manually verified the change by ...*

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented?
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

2025-01-09 17:14 UTC, PaddyMc requested changes
gg, one ask, it's kinda big tho

2025-01-09 17:14 UTC, PaddyMc commented on ingest/indexer/service/indexer_streaming_service_test.go
> +			transformedPools := []types.PoolI{}
Can we use `ingesttypes` instead of `types` or just `ingest`.PoolI{} ?

2025-01-10 09:50 UTC, deividaspetraitis commented on ingest/indexer/service/indexer_streaming_service_test.go
> +			transformedPools := []types.PoolI{}
Good catch, updated as per your suggestion, it's `ingesttypes` now instead of just `types`.

2025-01-10 11:12 UTC, PaddyMc approved these changes

2025-01-10 11:12 UTC, PaddyMc requested changes
Can we add a changelog please?

2025-01-10 11:58 UTC, PaddyMc approved these changes

2025-01-10 12:02 UTC, merged